<a href="https://colab.research.google.com/github/Elma-dev/twitterTweetClassifier/blob/main/TweetClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [173]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")
data=train

In [174]:
data.head()

TweetId     Label  \
0  304271250237304833  Politics   
1  304834304222064640  Politics   
2  303568995880144898    Sports   
3  304366580664528896    Sports   
4  296770931098009601    Sports   

                                           TweetText  
0  '#SecKerry: The value of the @StateDept and @U...  
1                            '@rraina1481 I fear so'  
2  'Watch video highlights of the #wwc13 final be...  
3  'RT @chelscanlan: At Nitro Circus at #AlbertPa...  
4  '@cricketfox Always a good thing. Thanks for t...

In [85]:
#data=data.drop(['TweetId'],axis=1)

In [175]:
X=data.TweetText
y=data.Label

##Remove Punctiation In Feature

In [176]:
from string import punctuation # punctuation = !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
import re #regular Expression
from nltk.tokenize.toktok import ToktokTokenizer #txt To token

tokenizer = ToktokTokenizer( ) 
cleanTweet=[]
allTokens=''

for word in X:
  #Remove URLs
  notUrl=re.sub(r'https?:\S*', '', word)
  #Remove Punct
  notPunc=notUrl.translate(str.maketrans('','',punctuation))
  #Toknize
  tokens = tokenizer.tokenize(notPunc)
  cleanTweet.append(tokens)
  allTokens+=' '.join(tokens)

#count each token redundancy
tokenCounter=dict()
for word in allTokens.split():
  if tokenCounter.get(word)==None:
    tokenCounter[word]=1
  else:
    tokenCounter[word]+=1
#remove token with coutn=1
pureToken=dict()
for k,v in tokenCounter.items():
  if(v!=1):
    pureToken[k]=v

#useFull Token in each Tweet
useTokenTweet=[]
for row in cleanTweet:
  l=[]
  for tok in row:
    if pureToken.get(tok)!=None:
      l.append(tok)
  useTokenTweet.append(l)

In [177]:
' '.join(useTokenTweet[0])

'SecKerry The value of the StateDept and USAID is measured not in dollars but in terms of our American'

In [178]:
data['pureTweet']=useTokenTweet

In [179]:
data.head()

TweetId     Label  \
0  304271250237304833  Politics   
1  304834304222064640  Politics   
2  303568995880144898    Sports   
3  304366580664528896    Sports   
4  296770931098009601    Sports   

                                           TweetText  \
0  '#SecKerry: The value of the @StateDept and @U...   
1                            '@rraina1481 I fear so'   
2  'Watch video highlights of the #wwc13 final be...   
3  'RT @chelscanlan: At Nitro Circus at #AlbertPa...   
4  '@cricketfox Always a good thing. Thanks for t...   

                                           pureTweet  
0  [SecKerry, The, value, of, the, StateDept, and...  
1                                      [I, fear, so]  
2  [Watch, video, highlights, of, the, wwc13, fin...  
3  [RT, chelscanlan, At, Nitro, Circus, at, Alber...  
4  [Always, a, good, thing, Thanks, for, the, fee...

In [180]:
pureToken.get('of')

1912

In [182]:
#DataEncoding:
data_encoding=data
data_encoding[list(pureToken.keys())]=np.zeros(len(list(pureToken.keys())))

In [267]:
for i in range(len(data_encoding)):
    for j in train['pureTweet'][i]:
        train[j].iloc[i]=1
  

<ipython-input-267-e1a28590faee>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[j].iloc[i]=1


In [215]:
from sklearn.preprocessing import LabelEncoder
labelEncoder=LabelEncoder()
data_encoding['Label']=labelEncoder.fit_transform(data_encoding.Label)

In [268]:
data_encoding.head()

TweetId  Label  \
0  304271250237304833      0   
1  304834304222064640      0   
2  303568995880144898      1   
3  304366580664528896      1   
4  296770931098009601      1   

                                           TweetText  \
0  '#SecKerry: The value of the @StateDept and @U...   
1                            '@rraina1481 I fear so'   
2  'Watch video highlights of the #wwc13 final be...   
3  'RT @chelscanlan: At Nitro Circus at #AlbertPa...   
4  '@cricketfox Always a good thing. Thanks for t...   

                                           pureTweet  SecKerry  The  value  \
0  [SecKerry, The, value, of, the, StateDept, and...       1.0  1.0    1.0   
1                                      [I, fear, so]       0.0  0.0    0.0   
2  [Watch, video, highlights, of, the, wwc13, fin...       0.0  0.0    0.0   
3  [RT, chelscanlan, At, Nitro, Circus, at, Alber...       0.0  0.0    0.0   
4  [Always, a, good, thing, Thanks, for, the, fee...       0.0  0.0    0.0   

    of  the  StateDept  ...  Keith  Vijays  DAY  Glasgow  Oil  base  flies  \
0  1.0  1.0        1.0  ...    0.0     0.0  0.0      0.0  0.0   0.0    0.0   
1  0.0  0.0        0.0  ...    0.0     0.0  0.0      0.0  0.0   0.0    0.0   
2  1.0  1.0        0.0  ...    0.0     0.0  0.0      0.0  0.0   0.0    0.0   
3  0.0  0.0        0.0  ...    0.0     0.0  0.0      0.0  0.0   0.0    0.0   
4  0.0  1.0        0.0  ...    0.0     0.0  0.0      0.0  0.0   0.0    0.0   

   TheReverendDan  Bresnan  RIP  
0             0.0      0.0  0.0  
1             0.0      0.0  0.0  
2             0.0      0.0  0.0  
3             0.0      0.0  0.0  
4             0.0      0.0  0.0  

[5 rows x 6838 columns]

In [269]:
#spliting Data
X=data_encoding.iloc[:,4:].values
y=data_encoding.Label.values

In [270]:
print(X)
print(y)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0 0 1 ... 1 1 0]


## Create ML Model

In [271]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [272]:
from sklearn.tree import DecisionTreeClassifier
decisionTree=DecisionTreeClassifier()
decisionTree.fit(x_train,y_train)

DecisionTreeClassifier()

In [273]:
y_predict=decisionTree.predict(x_test)

In [274]:
decisionTree.score(x_test,y_test)

0.8296568627450981

In [275]:
from sklearn.ensemble import RandomForestClassifier
rndForest=RandomForestClassifier() 
rndForest.fit(x_train,y_train)

RandomForestClassifier()

In [287]:
rndForest.score(x_test,y_test)

0.9099264705882353

In [277]:
from sklearn.linear_model import LogisticRegression
logisticReg=LogisticRegression()
logisticReg.fit(x_train,y_train)

LogisticRegression()

In [278]:
y_predict=logisticReg.predict(x_test)

In [279]:
logisticReg.score(x_test,y_test)

0.9375

In [281]:
x_train.sum()

64386.0

In [283]:
from sklearn.metrics import classification_report
pred = rndForest.predict(x_test)
print(classification_report(y_test, pred, target_names=("Politics", "Sports")))

              precision    recall  f1-score   support

    Politics       0.91      0.91      0.91       809
      Sports       0.91      0.91      0.91       823

    accuracy                           0.91      1632
   macro avg       0.91      0.91      0.91      1632
weighted avg       0.91      0.91      0.91      1632



In [289]:
from sklearn.metrics import f1_score
f1_score(y_test,y_predict)

0.9385542168674698

In [288]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predict)

0.7499816012748439